configurations:
  global:
    logLevel: info
    outputFormat: pretty
    pollIntervalMinutes: 60
    onlineCrlspath: /home/torb/HelseGitLab/trawler/crls/
  alarmathan:
    webhookURL: https://alarm.test.nhn.no/v1/webhook
    serviceid: "287"
    team: Allmenn sky
    cluster: Torb-Cluster
    app: PKI-Trawler
    varselTilOS: test
  onlineCrls:
  # List of online CRLs to monitor
  ## NHN online intermediates
  ### NHN Internal CA - TEST
  - Name: NHN Internal CA - TEST(2)
    URL: http://crl.nhn.no/crl/NHN%20Internal%20CA%20-%20TEST(2).crl
  ## DigiCert CRLs
  ### DigiCert EV RSA CA G2
  - Name: DigiCert EV RSA CA G2
    URL: http://crl4.digicert.com/DigiCertEVRSACAG2.crl
